/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package queue;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author PRACTICAS
 */
public class pantalla extends javax.swing.JFrame {
Queue<String> cola = new LinkedList<String>();
    /**
     * Creates new form pantalla
     */
    public pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BTNImprimir = new javax.swing.JButton();
        TXTInsertar = new javax.swing.JTextField();
        TXTImprimir = new javax.swing.JTextField();
        BTNingresar = new javax.swing.JButton();
        BTNContar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTBorrar = new javax.swing.JButton();
        BTNBuscar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        BTNImprimir.setText("Imprimir");
        BTNImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNImprimirActionPerformed(evt);
            }
        });

        TXTImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTImprimirActionPerformed(evt);
            }
        });

        BTNingresar.setText("Ingresar");
        BTNingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNingresarActionPerformed(evt);
            }
        });

        BTNContar.setText("Contador");
        BTNContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNContarActionPerformed(evt);
            }
        });

        jLabel1.setText("Insertar");

        jLabel2.setText("Imprimir");

        TXTBorrar.setText("Borrar");
        TXTBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBorrarActionPerformed(evt);
            }
        });

        BTNBuscar.setText("Buscar");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BTNingresar)
                                .addGap(29, 29, 29)
                                .addComponent(BTNImprimir)
                                .addGap(43, 43, 43)
                                .addComponent(BTNContar))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(BTNBuscar)
                                .addGap(53, 53, 53)
                                .addComponent(TXTBorrar)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNingresar)
                    .addComponent(BTNImprimir)
                    .addComponent(BTNContar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTBorrar)
                    .addComponent(BTNBuscar))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTImprimirActionPerformed

    private void BTNingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNingresarActionPerformed
        // TODO add your handling code here:
        cola.add(TXTInsertar.getText());
        JOptionPane.showMessageDialog(null,("Se inserto un dato en la cola"));
        TXTInsertar.setText("");
    }//GEN-LAST:event_BTNingresarActionPerformed

    private void BTNImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNImprimirActionPerformed
        // TODO add your handling code here:
      if(cola.isEmpty()==true){
             JOptionPane.showMessageDialog(null, "La cola esta vacia");
        }else{
            TXTImprimir.setText(cola.remove().toString());
        }
    }//GEN-LAST:event_BTNImprimirActionPerformed

    private void TXTBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBorrarActionPerformed
        // TODO add your handling code here:
        
        if(cola.isEmpty()==true){
            JOptionPane.showMessageDialog(null,"La cola esta vacia.");
        }
 else
        {
           TXTImprimir.setText(TXTImprimir.getText()+cola.poll().toString()+"-");
           
           JOptionPane.showMessageDialog(null,"ha eliminado el primer elemento de la cola Queue. "); 
        }
        
        
        
    }//GEN-LAST:event_TXTBorrarActionPerformed

    private void BTNContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNContarActionPerformed
        // TODO add your handling code here:
         
        if(cola.isEmpty()==true)
         
        {
            JOptionPane.showMessageDialog(null,"La cola Queue esta vacia.");
            
        }
        else
        { 
            JOptionPane.showMessageDialog(null,"En la cola Queue hay los siguientes elementos: "+cola.size());
        
        } 
        
        
        
    }//GEN-LAST:event_BTNContarActionPerformed

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        // TODO add your handling code here:
        Queue<String> colaBusqueda=cola;
   Boolean bandera=false;
   String valorBuscado=JOptionPane.showInputDialog("Ingrese elemento a buscar en la cola");
  
        
    if (cola.contains(valorBuscado)){
        JOptionPane.showMessageDialog(null, "El elemento: "+valorBuscado+" si se encuentra en la cola");
        }
        else{
        JOptionPane.showMessageDialog(null, "El elemento: "+valorBuscado+" NO se encuentra en la cola");
        }
   
      
       
        
        
    }//GEN-LAST:event_BTNBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNContar;
    private javax.swing.JButton BTNImprimir;
    private javax.swing.JButton BTNingresar;
    private javax.swing.JButton TXTBorrar;
    private javax.swing.JTextField TXTImprimir;
    private javax.swing.JTextField TXTInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
